version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3030 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - '3030:3030'
    depends_on:
      - db
    tty: true