version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    tty: true
    stdin_open: true
    depends_on:
      - db 
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - tmp-data:/myapp/tmp/sockets
      - public-data:/myapp/public

  db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  nginx:
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - tmp-data:/myapp/tmp/sockets
      - public-data:/myapp/public
    depends_on:
      - web 

volumes:
  public-data:
  tmp-data:
  log-data: