version: '3'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
      - tmp-data:/myapp/tmp/sockets
      - public-data:/myapp/public
      - log-data:/myapp/log
    depends_on:
      - db 

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: ./containers/nginx
    ports:
      - 80:80
    volumes:
      - tmp-data:/myapp/tmp/sockets
      - public-data:/myapp/public
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data: