version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: mv docker-compose.yml
          command: |
            mv Docker-compose.yml docker-compose.yml
            mv Dockerfile dockerfile
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-
      - run:
          name: Which bundler?
          command: bundle -v
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: docker-compose exec app bundle exec rake db:create
      - run: docker-compose exec app bundle exec rake db:schema:load
      - run:
          name: RSpecテスト実行
          command: docker-compose exec app bundle exec rspec
      - run:
          name: Rubocopテスト実行
          command: docker-compose exec app bundle exec rubocop
      - run:
          name: Dockerコンテナの停止
          command: docker-compose down