default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  pool: 5
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  
development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
